name:              backend
version:           0.0.1

ghc-options: -Wall -fwarn-tabs -fno-warn-type-defaults

flags:
  dev:
    description: Turn on development settings, like auto-reload templates.
    default: false
    manual: false
  library-only:
    description: Build for use with "yesod devel"
    default: false
    manual: false

default-extensions:
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base                          >= 4          && < 5
  - yesod                         >= 1.4.3      && < 1.5
  - yesod-core                    >= 1.4.17     && < 1.5
  - yesod-auth                    >= 1.4.0      && < 1.5
  - yesod-static                  >= 1.4.0.3    && < 1.6
  - yesod-form                    >= 1.4.0      && < 1.5
  - classy-prelude                >= 0.10.2
  - classy-prelude-conduit        >= 0.10.2
  - classy-prelude-yesod          >= 0.10.2
  - bytestring                    >= 0.9        && < 0.11
  - text                          >= 0.11       && < 2.0
  - persistent                    >= 2.0        && < 2.6
  - persistent-sqlite             >= 2.1.1      && < 2.6
  - persistent-template           >= 2.0        && < 2.6
  - template-haskell
  - shakespeare                   >= 2.0        && < 2.1
  - hjsmin                        >= 0.1        && < 0.3
  - monad-control                 >= 0.3        && < 1.1
  - wai-extra                     >= 3.0        && < 3.1
  - yaml                          >= 0.8        && < 0.9
  - http-conduit                  >= 2.1        && < 2.2
  - directory                     >= 1.1        && < 1.3
  - warp                          >= 3.0        && < 3.3
  - data-default
  - aeson                         >= 0.6        && < 0.12
  - conduit                       >= 1.0        && < 2.0
  - monad-logger                  >= 0.3        && < 0.4
  - fast-logger                   >= 2.2        && < 2.5
  - wai-logger                    >= 2.2        && < 2.4
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - foreign-store

library:
  exposed-modules:
    - Application
    - Foundation
    - Import
    - Import.NoFoundation
    - Model
    - Settings
    - Settings.StaticFiles
    - Handler.Common
    - Handler.Home
    - Handler.Comment
  when:
    - condition: flag(dev)
      then:
        cpp-options: -DDEVELOPMENT
        ghc-options: -O0
      else:
        ghc-options: -O2

executables:
  backend:
    main: main.hs
    source-dirs: app
    dependencies:
      - backend
    ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-N
